development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:b7f4e504668db5c3148fd57d4412638d@spinyfin.redistogo.com:11920/
  channel_prefix: cookbook_production
